apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: db
  name: db
  namespace: osiguranje-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
