apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: osiguranje-prod
  labels:
    service: gateway
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: gateway
status:
  loadBalancer: {}
