kubectl apply -f Gateway.yaml
kubectl apply -f Namespace.yaml
kubectl apply -f Configmap.yaml
kubectl apply -f Ingress.yaml
kubectl apply -f Mysql.yaml
kubectl apply -f Redis.yaml
kubectl apply -f AccountTransactions.yaml
kubectl apply -f BuyingMarket.yaml
kubectl apply -f Frontend.yaml
kubectl apply -f Otc.yaml
kubectl apply -f PythonFlask.yaml
kubectl apply -f Securities.yaml
kubectl apply -f Usercrud.yaml
