apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: osiguranje-prod
  labels:
    service: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: frontend
status:
  loadBalancer: {}
