apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercrud
  namespace: osiguranje-prod
  labels:
    service: usercrud
spec:
  replicas: 1
  selector:
    matchLabels:
      service: usercrud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: usercrud
        network/backend: "true"
    spec:
      containers:
        - env:
            - name: EUREKA_EXTERNAL_PORT
              value: "8761"
            - name: EUREKA_INTERNAL_PORT
              value: "8761"
            - name: FRONTEND_EXTERNAL_PORT
              value: "80"
            - name: FRONTEND_INTERNAL_PORT
              value: "80"
            - name: GATEWAY_EXTERNAL_PORT
              value: "8080"
            - name: GATEWAY_INTERNAL_PORT
              value: "8080"
            - name: MARKET_EXTERNAL_PORT
              value: "8092"
            - name: MARKET_INTERNAL_PORT
              value: "8092"
            - name: MYSQL_EXTERNAL_PORT
              value: "3307"
            - name: MYSQL_INTERNAL_PORT
              value: "3306"
            - name: MYSQL_NAME
              value: osiguranje
            - name: MYSQL_PASSWORD
              value: YZUhhNEXfAW8j7Qc
            - name: PYTHONFLASK_EXTERNAL_PORT
              value: "9999"
            - name: PYTHONFLASK_INTERNAL_PORT
              value: "5000"
            - name: SECURITIES_EXTERNAL_PORT
              value: "2000"
            - name: SECURITIES_INTERNAL_PORT
              value: "2000"
            - name: SPRING_DATASOURCE_PASSWORD
              value: YZUhhNEXfAW8j7Qc
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb:3306/osiguranje?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: USERCRUD_EXTERNAL_PORT
              value: "8091"
            - name: USERCRUD_INTERNAL_PORT
              value: "8091"
          image: ghcr.io/raf-si-2021/osiguranjeraf2022/user-crud
          name: usercrud
          ports:
            - containerPort: 8091
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /root/.m2
              name: usercrud
      restartPolicy: Always
      volumes:
        - name: usercrud
          persistentVolumeClaim:
            claimName: usercrud
status: {}
