apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: osiguranje-dev
  labels:
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: frontend
        network/ngnix: "true"
    spec:
      containers:
        - image: ghcr.io/raf-si-2021/osiguranjeraf2022/frontend
          name: frontend
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
