apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: osiguranje-dev
  labels:
    service: mysqldb
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    service: mysqldb
status:
  loadBalancer: {}
