apiVersion: v1
kind: Service
metadata:
  name: buyingmarket
  namespace: osiguranje-dev
  labels:
    service: buyingmarket
spec:
  ports:
    - name: "8092"
      port: 8092
      targetPort: 8092
  selector:
    service: buyingmarket
status:
  loadBalancer: {}
