apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: osiguranje-dev
  labels:
    service: eureka
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    service: eureka
status:
  loadBalancer: {}
