apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: osiguranje-dev
  labels:
    service: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eureka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: eureka
        network/backend: "true"
    spec:
      containers:
        - env:
            - name: EUREKA_EXTERNAL_PORT
              value: "8761"
            - name: EUREKA_INTERNAL_PORT
              value: "8761"
            - name: FRONTEND_EXTERNAL_PORT
              value: "80"
            - name: FRONTEND_INTERNAL_PORT
              value: "80"
            - name: GATEWAY_EXTERNAL_PORT
              value: "8080"
            - name: GATEWAY_INTERNAL_PORT
              value: "8080"
            - name: MARKET_EXTERNAL_PORT
              value: "8092"
            - name: MARKET_INTERNAL_PORT
              value: "8092"
            - name: MYSQL_EXTERNAL_PORT
              value: "3307"
            - name: MYSQL_INTERNAL_PORT
              value: "3306"
            - name: MYSQL_NAME
              value: osiguranje
            - name: MYSQL_PASSWORD
              value: YZUhhNEXfAW8j7Qc
            - name: PYTHONFLASK_EXTERNAL_PORT
              value: "9999"
            - name: PYTHONFLASK_INTERNAL_PORT
              value: "5000"
            - name: SECURITIES_EXTERNAL_PORT
              value: "2000"
            - name: SECURITIES_INTERNAL_PORT
              value: "2000"
            - name: USERCRUD_EXTERNAL_PORT
              value: "8091"
            - name: USERCRUD_INTERNAL_PORT
              value: "8091"
          image: ghcr.io/raf-si-2021/osiguranjeraf2022/eureka
          name: eureka
          ports:
            - containerPort: 8761
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /root/.m2
              name: eureka
      restartPolicy: Always
      volumes:
        - name: eureka
          persistentVolumeClaim:
            claimName: eureka
status: {}
