apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: osiguranje-prod
  labels:
    service: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: gateway
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/raf-si-2021/osiguranjeraf2022/gateway:latest
          name: gateway
          ports:
            - name: gateway
              containerPort: 8080
          resources: {}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: MYSQL_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: MYSQL_PASSWORD
            - name: ZUUL_ROUTES_USER_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: ZUUL_ROUTES_USER_URL
            - name: ZUUL_ROUTES_SECURITIES_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: ZUUL_ROUTES_SECURITIES_URL
            - name: ZUUL_ROUTES_BUYINGMARKET_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: ZUUL_ROUTES_BUYINGMARKET_URL
            - name: ZUUL_ROUTES_STOCKINFO_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: ZUUL_ROUTES_STOCKINFO_URL
            - name: ZUUL_ROUTES_TRANSACTION_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: ZUUL_ROUTES_TRANSACTION_URL
            - name: ZUUL_ROUTES_OTC_URL
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: ZUUL_ROUTES_OTC_URL
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: osiguranje-prod
  labels:
    service: gateway
spec:
  clusterIP: 10.96.0.14
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    service: gateway

