apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buyingmarket
  namespace: osiguranje-prod
  labels:
    service: buyingmarket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
