apiVersion: v1
kind: Service
metadata:
  name: usercrud
  namespace: osiguranje-dev
  labels:
    service: usercrud
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
  selector:
    service: usercrud
status:
  loadBalancer: {}
